name: Demo push with tags
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: ./.github/actions/push/action.yml
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 97629107673c93d1a4fc70.11630567
          base_lang: es
          translations_path: |
            packs/config/locales
            packs/foo/bar/baz/config/locales
            packs/foo/bar/baz/qux/config/locales
            packs/foo/bar/config/locales
            packs/foo/config/locales
          file_format: yml
          additional_params: --use-automations
          flat_naming: true