name: Demo push with tags
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: ./
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 97629107673c93d1a4fc70.11630567
          base_lang: es
          file_format: yml
          additional_params: "--convert-placeholders --hidden-from-contributors --use-automations"
